package:
  name: personal-website
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/mistervladimir/fijitools.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pyqt5

test:
  imports:
    -

about:
  home: https://github.com/mistervladimir/fijitools
  license: GNUv3
  license_file: LICENSE.rst