package:
  name: fijitools
  version: "v0.1.0-unstable"

source:
  git_rev: v0.2
  git_url: https://github.com/mistervladimir/fijitools.git

requirements:
  host:
    - python>=3.6
    - setuptools
    - ruamel.yaml

  run:
    - numpy
    - pyqt>=5.6
    - h5py
    - addict>=2.2.0
    - pandas
    - six
    - ruamel.yaml

test:
  commands:
    - python -m unittest discover -s test
  soure_files:
    - fijitools/test/data/*

about:
  home: https://github.com/mistervladimir/fijitools
  license: GNUv3
  license_file: LICENSE.rst