package:
  name: personal-website
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/mistervladimir/fijitools.git

requirements:
  host:
    - python
    - setuptools
    - pyyaml

  run:
    - numpy
    - pyqt5
    - h5py
    - addict
    - pandas
    - six
    - pyyaml

test:
  soure_files:
    - fijitools/test/data/*

about:
  home: https://github.com/mistervladimir/fijitools
  license: GNUv3
  license_file: LICENSE.rst